server:
  port: 9000
 
eureka:
  instance:
    hostname: localhost
    
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
      - id: user-service
        uri: lb://user-service
        predicates:
        - Path=/user/**
        
      - id: device-service
        uri: lb://device-service
        predicates:
        - Path=/device/**